spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "spin-teavm-example"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "spin_http"
source = "target/generated/wasm/teavm-wasm/classes.wasm"
allowed_http_hosts = [ "https://some-random-api.ml" ]
environment = { URL = "https://some-random-api.ml/facts/dog" }

[component.trigger]
route = "/..."

[component.build]
command = "mvn prepare-package"
